# Generated by Django 4.1.7 on 2023-03-12 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pel', '0004_alter_encode_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='encode',
            name='filename',
            field=models.CharField(default='encoded_image', max_length=100),
        ),
    ]
