# Generated by Django 4.1.3 on 2023-03-13 16:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('pel', '0005_encode_filename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='decode',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='encode',
            name='filename',
            field=models.CharField(max_length=100),
        ),
    ]
