# Generated by Django 4.1.3 on 2023-03-22 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pel', '0006_alter_decode_id_alter_encode_filename'),
    ]

    operations = [
        migrations.AddField(
            model_name='decode',
            name='key',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='encode',
            name='key',
            field=models.CharField(default='', max_length=10),
        ),
    ]
